### ISSUE TITLE
import script import_aan_elasticsearch.py runs into timeout 

### ISSUE THREAD

**Issue by mauermbq** [uhh-lt/lt-expertfinder#1]
Few seconds after executing import_aan_elasticsearch.py it runs into time out, see console log

(expertf) Marks-Mac:tools mark$ python import_aan_elasticsearch.py -a /opt/dev/DTIT/lt-expertfinder/aan
deleting 'aan' index...
 response: '{'acknowledged': True}'
creating 'aan' index...
 response: '{'acknowledged': True, 'shards_acknowledged': True, 'index': 'aan'}'
Importing bulk...
Traceback (most recent call last):
  File "/opt/dev/miniconda3/envs/expertf/lib/python3.6/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/opt/dev/miniconda3/envs/expertf/lib/python3.6/site-packages/urllib3/connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "/opt/dev/miniconda3/envs/expertf/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/opt/dev/miniconda3/envs/expertf/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/dev/miniconda3/envs/expertf/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/opt/dev/miniconda3/envs/expertf/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:
...

Container log:

[2019-06-15T15:49:28,125][INFO ][o.e.c.m.MetaDataDeleteIndexService] [TVO817O] [aan/TB09nSn9SVGb2RQvX6k3Tw] deleting index
[2019-06-15T15:49:28,525][INFO ][o.e.c.m.MetaDataCreateIndexService] [TVO817O] [aan] creating index, cause [api], templates [], shards [1]/[0], mappings [_doc]
[2019-06-15T15:49:28,817][INFO ][o.e.c.r.a.AllocationService] [TVO817O] Cluster health status changed from [YELLOW] to [GREEN] (reason: [shards started [[aan][0]] ...]).

**Comment by bigabig** [comment]
Importing the bulk data leads to a TimeOut exception if your hardware is not fast enough. I updated the script import_aan_elasticsearch.py. Now you can use the flag -t to set a custom timeout value in seconds. For example $ python3 import_aan_elasticsearch.py -a /path/to/elasticsearch -t 120.
